POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video Node",
    "description": "Segundo Video",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/130ace39-557f-46cb-be4d-3e59680cfcd1
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Primeiro Video",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/130ace39-557f-46cb-be4d-3e59680cfcd1